default:
  - build

build:
  - clean
  - lint
  - buildjs
  - buildcss
  - copy:example

lint:
  - jshint:lib
  - jscs:lib
  - lintspaces:lib

buildjs:
  - preprocess
  - concat
  - uglify

buildcss:
  - sass
  - cssmin
